/**:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 0.5
    ndt_num_threads: 4
    gicp_corr_dist_threshold: 0.5
    trans_for_mapupdate: 0.15
    vg_size_for_input: 0.25
    vg_size_for_map: 0.005
    use_min_max_filter: false
    scan_min_range: 0.01
    scan_max_range: 10.0
    scan_period: 0.01
    map_publish_period: 15.0
    num_targeted_cloud: 50
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    set_initial_pose: true
    use_odom: false
    use_imu: true