/**:
  ros__parameters:
    enable_debug_topics: true
  
    min_scan_time_offset: 0.0001
    max_path_points: 2           #NOTE: Currently it does not make much sense to havbe more than two path points. But wallfollowing still is written in a way that allows to add more points (but that may lead to strange results, only do after e.g. adjusting how old points are transformed and sorted out or checking current results.)
    target_method: "CENTER_PATH"
    
    prediction_min_distance: 0.1
    prediction_max_distance: 5.0
    prediction_time: 0.01
    prediction_average_weight: 5.0
    
    target_min_distance: 0.7
    target_collision_precision: 0.0001
    
    max_yaw_deviation: 0.7
    
    stop_detection_speed_threshold: 0.1
    
    max_longitudinal_velocity_mps:  50.0 #100.0
    max_lateral_velocity_mps: 0.0
    max_heading_rate_rps: 0.0