/**:
  ros__parameters:
    regularization_enabled: False
    input_sensor_points_queue_size: 0
    trans_epsilon: 0.01
    step_size: 0.1
    resolution: 0.1
    max_iterations: 5
    neighborhood_search_method: 0
    num_threads: 1
    converged_param_type: 0
    converged_param_transform_probability: 4.5
    converged_param_nearest_voxel_transformation_likelihood: 2.3
    initial_estimate_particles_num: 100
    initial_pose_timeout_sec: 1.0
    initial_pose_distance_tolerance_m: 1.0
    output_pose_covariance: [0.0, 0.0]