/**:
  ros__parameters:
    max_velocity: 1000.0
    max_accel: 1000.0
    min_decel: -500.0
    max_jerk: 1000.0
    min_jerk: -500.0
    margin_to_insert_external_velocity_limit: 0.3
    max_lateral_accel: 1000.0
    min_curve_velocity: 0.274
    decel_distance_before_curve: 0.25
    decel_distance_after_curve: 0.2
    min_decel_for_lateral_acc_lim_filter: -250.0
    replan_vel_deviation: 553.0
    engage_velocity: 0.0
    engage_acceleration: 0.0
    engage_exit_ratio: 1.0
    stop_dist_to_prohibit_engage: 0.05
    stopping_velocity: 0.0
    stopping_distance: 0.0
    extract_ahead_dist: 20.0
    extract_behind_dist: 5.0
    delta_yaw_threshold: 1.0472
    max_trajectory_length: 20.0
    min_trajectory_length: 3.0
    resample_time: 1.0
    dense_dt: 0.01
    dense_min_interval_distance: 0.01
    sparse_dt: 0.05
    sparse_min_interval_distance: 0.4
    post_max_trajectory_length: 30.0
    post_min_trajectory_length: 3.0
    post_resample_time: 1.0
    post_dense_dt: 0.01
    post_dense_min_interval_distance: 0.01
    post_sparse_dt: 0.01
    post_sparse_min_interval_distance: 0.1
    max_steering_angle_rate: 40.0
    resample_ds: 0.01
    curvature_threshold: 0.2
    curvature_calculation_distance: 0.1
    jerk_weight: 1.0
    over_v_weight: 10000.0
    over_a_weight: 5000.0
    over_j_weight: 100.0
    over_stop_velocity_warn_thr: 13.89
    
    ego_nearest_dist_threshold: 1.0
    ego_nearest_yaw_threshold: 1.0
