/**:
  ros__parameters:
    show_debug_info: False
    predict_frequency: 50.0
    tf_rate: 10.0
    enable_yaw_bias_estimation: True
    extend_state_step: 50
    pose_additional_delay: 0.0
    pose_gate_dist: 10000.0
    pose_smoothing_steps: 5
    twist_additional_delay: 0.0
    twist_gate_dist: 10000.0
    twist_smoothing_steps: 2
    proc_stddev_vx_c: 5.0
    proc_stddev_wz_c: 1.0
    proc_stddev_yaw_c: 0.005