/**:
  ros__parameters:
    ego_nearest_dist_threshold: 1.0
    ego_nearest_yaw_threshold: 1.0
    
    delay_compensation_time: 0.17

    enable_smooth_stop: true
    enable_overshoot_emergency: false
    enable_large_tracking_error_emergency: false
    enable_slope_compensation: false
    enable_keep_stopped_until_steer_convergence: false

    # state transition
    drive_state_stop_dist: 0.0 # 0.05 # Set to 0.0 to keep vehicle from stopping at close path points
    drive_state_offset_stop_dist: 0.0 # 0.1 # Set to 0.0 to make vehicle start even for near path points
    stopping_state_stop_dist: 0.049
    stopped_state_entry_duration_time: 0.1
    stopped_state_entry_vel: 0.1
    stopped_state_entry_acc: 0.1
    emergency_state_overshoot_stop_dist: 0.15 # TODO: Maybe set to 0.0 # Makes vehicle stop if velocity is 0.0 and we are near the end of the trajectory or the 0.0 speed point
    emergency_state_traj_trans_dev: 3.0
    emergency_state_traj_rot_dev: 1.0 #0.7

    # drive state
    kp: 1.0
    ki: 0.1
    kd: 0.0
    max_out: 1.0
    min_out: -1.0
    max_p_effort: 1.0
    min_p_effort: -1.0
    max_i_effort: 0.3
    min_i_effort: -0.3
    max_d_effort: 0.0
    min_d_effort: 0.0
    lpf_vel_error_gain: 0.9
    current_vel_threshold_pid_integration: 0.5
    enable_brake_keeping_before_stop: false
    brake_keeping_acc: -0.2

    # smooth stop state
    smooth_stop_max_strong_acc: -0.5
    smooth_stop_min_strong_acc: -1.0
    smooth_stop_weak_acc: -0.3
    smooth_stop_weak_stop_acc: -0.8
    smooth_stop_strong_stop_acc: -3.4
    smooth_stop_max_fast_vel: 0.5
    smooth_stop_min_running_vel: 0.01
    smooth_stop_min_running_acc: 0.01
    smooth_stop_weak_stop_time: 0.8
    smooth_stop_weak_stop_dist: -0.03
    smooth_stop_strong_stop_dist: -0.05

    # stopped state
    stopped_vel: 0.0
    stopped_acc: -5.0
    stopped_jerk: -5.0

    # emergency state
    emergency_vel: 0.0
    emergency_acc: -5.0
    emergency_jerk: -5.0

    # acceleration limit
    max_acc: 5.0
    min_acc: -5.0

    # jerk limit
    max_jerk: 5.0
    min_jerk: -5.0

    # pitch
    use_trajectory_for_pitch_calculation: false
    lpf_pitch_gain: 0.95
    max_pitch_rad: 0.1
    min_pitch_rad: -0.1