robot:
  dimensions:
    length: 0.205
    width: 0.675
    height: 0.215
    wheelbase: 0.33
  plugins:
    drive:
      rate: 10.0
      max_steer: 0.453786
      max_speed: 1.5
    joint_state_publisher:
      rate: 10.0
    laser:
      rate: 60.0
    camera:
      rate: 60.0

      