/**:
  ros__parameters:
    wheel_radius: 0.05
    wheel_width: 0.045
    wheel_base: 0.32
    wheel_tread: 1.0
    front_overhang: 0.0
    rear_overhang: 0.0
    left_overhang: 0.0
    right_overhang: 0.0
    vehicle_height: 0.1
    max_steer_angle: 90.0
    length: 0.49
    width: 0.18
    height: 0.1