/**:
  ros__parameters:
    wheel_radius: 0.0055 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.0045 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.033 # between front wheel center and rear wheel center
    wheel_tread: 0.025 # between left wheel center and right wheel center
    front_overhang: 0.008 # between front wheel center and vehicle front
    rear_overhang: 0.0125 # between rear wheel center and vehicle rear
    left_overhang: 0.002125 # between left wheel center and vehicle left
    right_overhang: 0.002125 # between right wheel center and vehicle right
    vehicle_height: 0.0215
    max_steer_angle: 0.453786 # [rad]

# I hope the params are in meters. But it is not documented.
